MVCTicket/Controllers/ProjectController.cs
using MVCTicket.CodeFirstDB;
using MVCTicket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTicket.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        public TicketContext db = new TicketContext();
        // GET: Project
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectViewModel model)
        {
            Project newProject = new Project();
            newProject.Name = model.Name;
            db.Projects.Add(newProject);
            db.SaveChanges();
            return View("Index",db.Projects.ToList());
        }
    }
}

MVCTicket/Controllers/TicketController.cs
using MVCTicket.CodeFirstDB;
using MVCTicket.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MVCTicket.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        public TicketContext db = new TicketContext();
        // GET: Ticket
        public ActionResult Index()
        {
            return View(db.Tickets.ToList());
        }

        public ActionResult Create()
        {
            TicketViewModel newTicket = new TicketViewModel();
            newTicket.ProjectList = new SelectList(db.Projects, "ProjectId", "Name");//from g in db.Projects select new Project { ProjectId = g.ProjectId("Key"), Name = g.Name("Display") };
            return View(newTicket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public RedirectResult Create(TicketViewModel model)
        {
            Ticket newTicket = new Ticket();
            newTicket.Title = model.Title;
            newTicket.Type = model.Type;
            newTicket.State = model.State;
            newTicket.Discription = model.Discription;
            newTicket.UserId = User.Identity.GetUserId();

            Project p = db.Projects.Single(foo => foo.ProjectId == model.ProjectId);
            newTicket.Project = p;

            db.Tickets.Add(newTicket);
            db.SaveChanges();

            return Redirect("~/Ticket/Index");
        }



        public RedirectResult TicketStarted(int ticketId)
        {
            Ticket newTicket = db.Tickets.Single(foo => foo.TicketId == ticketId);
            newTicket.Started = DateTime.Now;
            newTicket.State = State.Started;
            db.SaveChanges();
            return Redirect("~/Ticket/Index");
        }



        public RedirectResult TicketFinished(int ticketId)
        {
            Ticket newTicket = db.Tickets.Single(foo => foo.TicketId == ticketId);
            newTicket.Finished = DateTime.Now;
            newTicket.State = State.Finished;
            db.SaveChanges();
            return Redirect("~/Ticket/Index");
        }

        public ActionResult Delete(int ticketId)
        {
            Ticket ticketModel = db.Tickets.Single(foo => foo.TicketId == ticketId);
            return View(ticketModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int ticketId)
        {
            Ticket ticketModel = db.Tickets.Single(foo => foo.TicketId == ticketId);
            db.Tickets.Remove(ticketModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MVCTicket/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

MVCTicket/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

MVCTicket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")" type="text/javascript"> </script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Tickets", "Index", "Ticket")</li>
                    <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

MVCTicket/Views/Shared/_TicketList.cshtml
@model IEnumerable<MVCTicket.Models.Ticket>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Started)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Finished)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Single().Project.Name)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Started)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Finished, "ShortDateTime")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                <div class="btn-group btn-group-xs">
                    <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Edit", new { ticketId = item.TicketId })'">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                    <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Detail", new { ticketId = item.TicketId })'">
                        <span class="glyphicon glyphicon-info-sign"></span>
                    </button>
                    <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Delete", new { ticketId = item.TicketId})'">
                        <span class="glyphicon glyphicon-remove-sign"></span>
                    </button>
                    @if (item.State == MVCTicket.Models.State.UnStarted || item.State == MVCTicket.Models.State.Rejected)
                    {
                        <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("TicketStarted", new { ticketId = item.TicketId })'">
                            <span class="glyphicon glyphicon-play"></span>
                        </button>
                    }
                    else if (item.State == MVCTicket.Models.State.Started)
                    {
                        <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("TicketFinished", new { ticketId = item.TicketId })'">
                            <span class="glyphicon glyphicon-stop"></span>
                        </button>
                    }
                    else if (item.State == MVCTicket.Models.State.Finished)
                    {
                        <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("TicketAccept", new { ticketId = item.TicketId })'">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                        <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("TicketReject", new { ticketId = item.TicketId })'">
                            <span class="glyphicon glyphicon-exclamation-sign"></span>
                        </button>
                    }
                </div>

            </td>

            @*<td>
                    @if (item.State == MVCTicket.Models.State.UnStarted)
                    {
                        @Html.ActionLink("Start", "TicketStarted", new { ticketId = item.TicketId })
                    }
                    else if (item.State == MVCTicket.Models.State.Started)
                    {
                        @Html.ActionLink("Finished", "TicketFinished", new { ticketId = item.TicketId })
                    }



                </td>*@
        </tr>
    }

</table>

MVCTicket/Views/Shared/_TicketListGridView.cshtml
@using MVCTicket.Models;
@inherits System.Web.Mvc.WebViewPage<IEnumerable<Ticket>>
@using GridMvc.Html



@Html.Grid(Model).Named("expenseReportGrid").Columns(columns =>
           {
               columns.Add(foo => foo.Title).SetWidth(110);
               columns.Add(foo => foo.Discription).Sortable(false);
               columns.Add(foo => foo.Project.Name).Titled("Project Name").Filterable(true);
               columns.Add(foo => foo.Type).Sortable(true);
               columns.Add(foo => foo.Started).Sortable(true);
           }).WithPaging(20).Filterable().WithMultipleFilters()

<script>
    var selectedRow;
    $(function () {
        pageGrids.expenseReportGrid.onRowSelect(function (e) {
            
            //alert(e.row);
        });
    });
</script>